import type { Config } from 'tailwindcss';

export default {
	content: ['./app/**/{**,.client,.server}/**/*.{js,jsx,ts,tsx}'],
	theme: {
		extend: {
			fontFamily: {
				sans: [
					'"Inter"',
					'ui-sans-serif',
					'system-ui',
					'sans-serif',
					'"Apple Color Emoji"',
					'"Segoe UI Emoji"',
					'"Segoe UI Symbol"',
					'"Noto Color Emoji"',
				],
			},
		},
		colors: {
			yellow: {
				1: 'var(--yellow-1)',
				2: 'var(--yellow-2)',
				3: 'var(--yellow-3)',
				4: 'var(--yellow-4)',
				5: 'var(--yellow-5)',
				6: 'var(--yellow-6)',
				7: 'var(--yellow-7)',
				8: 'var(--yellow-8)',
				9: 'var(--yellow-9)',
				10: 'var(--yellow-10)',
				11: 'var(--yellow-11)',
				12: 'var(--yellow-12)',
				a1: 'var(--yellow-a1)',
				a2: 'var(--yellow-a2)',
				a3: 'var(--yellow-a3)',
				a4: 'var(--yellow-a4)',
				a5: 'var(--yellow-a5)',
				a6: 'var(--yellow-a6)',
				a7: 'var(--yellow-a7)',
				a8: 'var(--yellow-a8)',
				a9: 'var(--yellow-a9)',
				a10: 'var(--yellow-a10)',
				a11: 'var(--yellow-a11)',
				a12: 'var(--yellow-a12)',
				contrast: 'var(--yellow-contrast)',
				surface: 'var(--yellow-surface)',
				indicator: 'var(--yellow-indicator)',
				track: 'var(--yellow-track)',
			},
			gray: {
				1: 'var(--gray-1)',
				2: 'var(--gray-2)',
				3: 'var(--gray-3)',
				4: 'var(--gray-4)',
				5: 'var(--gray-5)',
				6: 'var(--gray-6)',
				7: 'var(--gray-7)',
				8: 'var(--gray-8)',
				9: 'var(--gray-9)',
				10: 'var(--gray-10)',
				11: 'var(--gray-11)',
				12: 'var(--gray-12)',
				a1: 'var(--gray-a1)',
				a2: 'var(--gray-a2)',
				a3: 'var(--gray-a3)',
				a4: 'var(--gray-a4)',
				a5: 'var(--gray-a5)',
				a6: 'var(--gray-a6)',
				a7: 'var(--gray-a7)',
				a8: 'var(--gray-a8)',
				a9: 'var(--gray-a9)',
				a10: 'var(--gray-a10)',
				a11: 'var(--gray-a11)',
				a12: 'var(--gray-a12)',
				contrast: 'var(--gray-contrast)',
				surface: 'var(--gray-surface)',
				indicator: 'var(--gray-indicator)',
				track: 'var(--gray-track)',
			},
		},
	},
	plugins: [],
} satisfies Config;
