steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', '${_IMAGE_SHA}', '-t', '${_IMAGE_LATEST}', '.']
    id: Build

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '${_IMAGE}'
      - '--all-tags'
    id: Push

  - id: 'Configuring as multicontainer Cloud Run service'
    waitFor: ['Push']
    name: 'gcr.io/cloud-builders/gcloud'
    script: |
      #!/bin/bash
      echo "Running entrypoint script..."
      ./etc/bin/deploy.sh || touch /workspace/deploy-failed
    env:
      - 'BUILD_ID=$BUILD_ID'
      - '_REGION=$_REGION'
      - '_SERVICE_NAME=$_SERVICE_NAME'
      - '_REFERENCE_DIGEST=$_IMAGE_SHA'
images:
  - '${_IMAGE_SHA}'
  - '${_IMAGE_LATEST}'
options:
  dynamic_substitutions: true
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _DEPLOY_REGION: us-central1
  _GCR_HOSTNAME: us-docker.pkg.dev
  _PLATFORM: managed
  _SERVICE_NAME: piscesmetadata-mainpage
  _IMAGE: 'us-docker.pkg.dev/www-central/piscesmetadata/mainpage'
  _IMAGE_SHA: '${_IMAGE}:${COMMIT_SHA}'
  _IMAGE_LATEST: '${_IMAGE}:latest'
  _CLOUDSDK_COMPUTE_ZONE: 'us-central1-a'
  _CLOUDSDK_COMPUTE_REGION: 'us-central1-a'
tags:
  - piscesmetadata
