apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: 'MC_SERVICE_NAME'
  labels:
    cloud.googleapis.com/location: 'REGION'
  annotations:
    run.googleapis.com/launch-stage: BETA
    run.googleapis.com/description: 'Multi-container service with sidecar'
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/container-dependencies: '{reverse-proxy: [app]}'
    spec:
      containers:
        # A) Serving ingress container "nginx" listening at PORT 8080
        # Main entrypoint of multi-container service.
        # Source is stored in nginx_mainpage_config secret in Secret Manager.
        # Any pings to this container will proxy over to hello container at PORT 8888.
        # https://cloud.google.com/run/docs/container-contract#port
        - image: nginx
          name: reverse-proxy
          ports:
            - name: http1
              containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: nginx-conf-secret
              readOnly: true
              mountPath: /etc/nginx/conf.d/
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 8080
        - image: '{image-placeholder}'
          name: app
          env:
            - name: PORT
              value: '3000'
            - name: NODE_ENV
              value: 'production'
            - name: APP_NAME
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: app_mainpage_env_appname
            - name: GOOGLE_TAG_MANAGER
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: app_mainpage_env_googletagmanagerid
            - name: APP_DESCRIPTION
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: app_mainpage_env_appdescription
            - name: APP_KEYWORDS
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: app_mainpage_env_appkeywords
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 3000
      volumes:
        - name: nginx-conf-secret
          secret:
            secretName: nginx_mainpage_config
            items:
              - key: latest
                path: default.conf
